### ISSUE TITLE
ionic-native対応について

### ISSUE THREAD

**Issue by ogmso** [nrikiji/cordova-line-login-plugin#11]
先日はご対応頂きまして有難うございました。
ご相談なのですが、cordova-line-login-pluginをラッパーするIonic Nativeプラグインの作成のご対応をお願いをしたいのですが可能でしょうか。
何卒、よろしくお願い致します。

**Comment by ogmso** [comment]
ご対応していただけるとの事有難うございます。
よろしくお願い致します。

**Comment by nrikiji** [comment]
```
$ ionic cordova plugin add https://github.com/nrikiji/cordova-line-login-plugin.git --variable LINE_CHANNEL_ID={your_line_channel_id}
$ npm install https://github.com/nrikiji/cordova-line-login-plugin/raw/master/ionic-native/dist/ionic-native-line-login-4.15.0.tgz
```
遅くなりましたが、上記の形でインストールできます。
ionic-nativeプラグインの開発は初めてでレポジトリの管理方法で悩んだのですが、皆さんはどのように管理されているか教えていただけないでしょうか？

**Comment by nrikiji** [comment]
https://github.com/ionic-team/ionic-native/pull/2782
ionic-nativeへPR中のためクローズとします
