### ISSUE TITLE
LINE SDK Ver5対応

### ISSUE THREAD

**Issue by nrikiji** [nrikiji/cordova-line-login-plugin#14]

**Comment by kazyumaru** [comment]
お世話になっております。
Cordova 8.0 / Ionic 4.1 / Cordova Android 7.1.1
上記環境でのビルドにおいて、ログイン時の連携画面が開かなくなりました。
ログにはエラーがCan't resolve *.ngfactory.jsというものが出ております。

Version 5への対応、心待ちにしております。

**Comment by nrikiji** [comment]
https://github.com/nrikiji/cordova-line-login-plugin/issues/16
SDKのバージョンアップとは別の原因のため別途issueを作成いたしました。

**Comment by nrikiji** [comment]
iOSのみリリースした

[0a74433267d53cf99437ee42fe3b0b42777e3bf3](https://github.com/nrikiji/cordova-line-login-plugin/commit/0a74433267d53cf99437ee42fe3b0b42777e3bf3)

**Comment by nrikiji** [comment]
version0.7でandroidもリリースした
