### ISSUE TITLE
Xcode IOS Build Error No such module 'LineSDK' LineLogin.swift

### ISSUE THREAD

**Issue by cakeboxsolutions** [nrikiji/cordova-line-login-plugin#18]
I try to build ios and have error say
No such module 'LineSDK' in LineLogin.swift file

**Comment by nrikiji** [comment]
What is the version of xcode?
Is LineSDK.framework set in "Linked Framework and Libraries"?
Is "platform/ios/{PROJECT_NAME}/Plugins/cordova-line-login-plugin" correctly copied?

try platform update
```
$ ionic corodva platform rm ios
$ ionic cordova platform add ios@latest
```
or
try plugin rm and add.
Still it will not work?

**Comment by cakeboxsolutions** [comment]
> What is the version of xcode?
> Is LineSDK.framework set in "Linked Framework and Libraries"?
> Is "platform/ios/{PROJECT_NAME}/Plugins/cordova-line-login-plugin" correctly copied?
> 
> try platform update
> 
> ```
> $ ionic corodva platform rm ios
> $ ionic cordova platform add ios@latest
> ```
> or
> try plugin rm and add.
> Still it will not work?

Is LineSDK.framework set in "Linked Framework and Libraries"? = YES
Is "platform/ios/{PROJECT_NAME}/Plugins/cordova-line-login-plugin" correctly copied? = YES
re-install platform = Still not work
re-install plugins = Still not work

Xcode version 10.1

**Comment by nrikiji** [comment]
sorry...
Would you please tell me the versions of node, cordova, npm?

**Comment by cakeboxsolutions** [comment]
> sorry...
> Would you please tell me the versions of node, cordova, npm?

node v8.9.1
cordova 8.1.2
npm 5.6.0
ionic 3.19.1

**Comment by cakeboxsolutions** [comment]
[https://imgur.com/a/y77AD2q](url)

**Comment by nrikiji** [comment]
I corrected it so I fixed it.
In my environment I can now build it. Please confirm.
Please update platform and plugin.

**Comment by cakeboxsolutions** [comment]
> It is thought that it is caused by plugman that the following symbolic links are not copied.
> I deleted the framework symbolic link and responded. Please confirm.
> It is probably a solution.

It fixed for me thank you.
