### ISSUE TITLE
[ERROR] An error occurred while running subprocess cordova.

### ISSUE THREAD

**Issue by xuelabi123** [nrikiji/cordova-line-login-plugin#23]
```
cordova build ios
##### Create Cartfile
##### Update Carthage
carthage bootstrap --platform iOS --cache-builds
Error: console.err is not a function
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```
when run cordova build ios, then I got this error.
anyone can help me?

**Comment by nrikiji** [comment]
https://github.com/nrikiji/cordova-plugin-carthage-support/commit/7094cb25271958cf1843b816e72802e3b7735617

sorry...
Since there was a typo, please re-execute and tell me the content of the error.
Please let me know the cordova and node version if you can.

**Comment by nrikiji** [comment]
Maybe there is no carthage...?
