### ISSUE TITLE
I want get Line person email data

### ISSUE THREAD

**Issue by redfire29** [nrikiji/cordova-line-login-plugin#24]
https://github.com/nrikiji/cordova-line-login-plugin/blob/master/src/ios/LineLogin.swift#L22

i use this code
https://developers.line.biz/en/docs/ios-sdk/swift/managing-users/

i change code like this 
`LoginManager.shared.login(permissions: [.profile, .openID, .email]`

i can get person email, so can you add a variable to control the `permissions: []` array?

**Comment by nrikiji** [comment]
Thank you very much. I have a desire to get emails, and I would like to respond.

**Comment by redfire29** [comment]
yes, both android & ios.
but I don't know how to write native code.
so......
can you help me
thanks

**Comment by nrikiji** [comment]
https://github.com/nrikiji/cordova-line-login-plugin/tree/feature/add_email

thanks.
Would you like to publicize the ios fix on this branch?

**Comment by redfire29** [comment]
sorry,  
I can't write native code.  

申し訳ありませんが、ネイティブプログラムは変更しません。

**Comment by nrikiji** [comment]
https://github.com/redfire29/cordova-line-login-plugin/commit/d4eddbb2e58fc21e4d0b9b5e2f4657fb95d1aa87

Does this code work?
Are you sure you want to use this for the ios version?

**Comment by nrikiji** [comment]
It has been confirmed that you can get Email with the program you reference. The android version is compatible. thanks

**Comment by nrikiji** [comment]
fixed
Supported ios and android with version 0.7.
