### ISSUE TITLE
Monaca上で利用することは可能でしょうか

### ISSUE THREAD

**Issue by nomori7010** [nrikiji/cordova-line-login-plugin#32]
ハイブリッドアプリ開発環境であるMonacaへのインポートを試みましたが、Monaca上では動作しませんでした。
Monaca上でもインポートして利用できるように変更するご予定はございますか？

例えば

https://github.com/jeduan/cordova-plugin-facebook4
https://github.com/ManifestWebDesign/twitter-connect-plugin

はMonaca上での利用が可能です。

**Comment by nrikiji** [comment]
Monacaは使ったことがないので試してみようとしましたが、無料プランではcustomなプラグインのインストールが行えないようで確認できませんでした。エラーなどでてましたら、詳細をいただけますと幸いです。また、ご利用のCordovaのバージョン等もいただけますと幸いです。

**Comment by nomori7010** [comment]
ご返答いただき誠にありがとうございました。

現状でMonacaで利用しているCordovaバージョンは9.0.0になっています。

Monaca上で下記のコードを実行すると、

```
function line_login(){
    navigator.lineLogin.login({},
        function(result) {
          console.log(result); // {userID:12345, displayName:'user name', pictureURL:'thumbnail url'}
        }, function(error) {
          console.log(error);
        });
}
```

次のエラーが発生します。

`TypeError:undefined is not an object (evaluating 'navigator.lineLogin.login')`


Monacaではビルド時に使用する「Xcode」用プロジェクトを手動で変更することはできないようです。
ビルド時に使用する「Xcode」用の設定をCordovaプラグイン側で行っていただければ動くかもしれません。

以上私の知っている情報をお伝えしておきます。

**Comment by nrikiji** [comment]
ご連絡ありがとうございます。

https://github.com/nrikiji/cordova-line-login-plugin/issues/33
cordova9での検証が必要そうなのでまずはこちらを検証させていただきます

また、当プラグインでは navigatorにlineLoginを入れてないのですが、Monacaではいずれのプラグインでもそのような使い方になるのでしょうか？

**Comment by nrikiji** [comment]
cordova9でのエラーが確認できたので対応してアップデートしました。
また、問題あればご連絡いただけますと幸いです。

**Comment by nomori7010** [comment]
ご対応ありがとうございます。

> また、当プラグインでは navigatorにlineLoginを入れてないのですが、Monacaではいずれのプラグインでもそのような使い方になるのでしょうか？

そうですね。少なくとも私が使ったことのあるMonaca上のCordovaプラグインは全てそういった形で呼び出しております。

> また、確認いただいたcordova-iosとcordova-androidのバージョンもいただけないでしょうか。
ご確認お願いいたします。

申し訳ございません。Monacaではcordova-iosとcordova-androidのバージョンについては意識して利用することがないのでどこを見ていいのかわかりません。分かり次第お伝えさせていただきます。

**Comment by nrikiji** [comment]
ご連絡ありがとうございます。
各種バージョン情報ついてもREADMEに記載させていただきましたのでご確認お願いします。
本件についてはクローズとさせていただきましたのでまた不都合ありましたらご連絡いただけますと幸いです。

**Comment by nomori7010** [comment]
こちらは`navigator.lineLogin`で呼び出しが可能になったということでしょうか？

**Comment by nrikiji** [comment]
失礼いたしました。
navigatorの件は失念しておりました、、

少なくとも、lineLogin.メソッド名では呼び出し可能かと思うのですが１度こちらでご確認いただけないでしょうか。

また、こちらで試せないのでnavigatorでの結果も頂けますと幸いです。

**Comment by nomori7010** [comment]
下記のコードを実行したところ、

`lineLogin.initialize({channel_id: "0000000000"});`

Monacaでは次のエラーが返されました。

`ReferenceError: Can't find variable: lineLogin`

またnavigatorをつけて、

`navigator.lineLogin.initialize({channel_id: "0000000000"});`

と実行すると、

`TypeError:undefined is not an object (evaluating 'navigator.lineLogin.initialize')`

というエラーが発生します。

以上こちらで試してみた結果になります。


Monaca環境ですと、READ MEに記述がされている

> 4. xcodeの「Capabilities」より「Keychain Sharing」をONに設定。

の設定はできません。

こちらも参考情報として付け加えさせていただきます。

**Comment by nrikiji** [comment]
Monacaの運営会社に問い合わせてみました。
回答ありしだいできる限り対応したいと思います。

**Comment by nomori7010** [comment]
ありがとうございます。実現できますと大変助かります。

**Comment by nrikiji** [comment]
度々申し訳ございません。
運営会社に問い合わせたところ通常のCordovaプラグインを使用可能との返答をいただきました。
また、トライアル期間であればカスタムプラグインの利用も可能とのことで試しているのですが、いただいた内容と同じエラーとなります、、

https://github.com/jeduan/cordova-plugin-facebook4
こちらのプラグインを入れてみたのですが私の環境では同様のエラーとなるのですが、プラグインをインストールする以外に必要な作業がありますでしょうか？

![Image from iOS (4)](https://user-images.githubusercontent.com/4780752/61705188-48c80d00-ad80-11e9-9afb-12b1c9a76698.png)
また、組み込んだプラグインのiOSとAndroidのアイコンが有効にならないのですがこちらの状態でも使用できるものなのでしょうか？

逆に質問する形で申し訳ありませんがご確認お願いいたします。

**Comment by nomori7010** [comment]
Facebookログインプラグインの使用方法については[Monacaのドキュメント](https://docs.monaca.io/ja/sampleapp/samples/facebook_sso/)で解説されているようです。

> また、組み込んだプラグインのiOSとAndroidのアイコンが有効にならないのですがこちらの状態でも使用できるものなのでしょうか？

確定的なことはわからないのですが、先日私がこの件について問い合わせたあと、ソースコードの修正をしていただいたと思います。
修正前はアイコンが有効になっていなかったのですが、修正後はアイコンが有効になりました。
情報としてお役に立てるかわかりませんがお伝えしておきます。

また、例えば下記のプラグインについては問題なく動作しております。

- cordova-plugin-app-version
- cordova-plugin-vibration
- cordova-plugin-geolocation

**Comment by nrikiji** [comment]
すみませんが、一旦対応予定がないのでクローズとさせていただきます
