### ISSUE TITLE
Pure Javascript Problem.

### ISSUE THREAD

**Issue by stanma9107** [nrikiji/cordova-line-login-plugin#34]
I am a student from Taiwan,
and I want to develop a Cordova app to my school,
but I just want to use pure javascript without any framework.
Can you give a example with Pure Javascript please?

**Comment by nrikiji** [comment]
thank you for example.

```
document.addEventListener('deviceready', function() {
  window.lineLogin.initialize({channel_id: "your_chanel_id"});
  ・・・
});
```

Please listen if you have any questions.
