### ISSUE TITLE
Use of undeclared identifier 'LineSDKLoginManager'

### ISSUE THREAD

**Issue by cakeboxsolutions** [nrikiji/cordova-line-login-plugin#38]
I get Error: Use of undeclared identifier 'LineSDKLoginManager' in AppDelegate+LineLogin.m
https://imgur.com/a/u07bcYk

Please help me. I try to fix it around 7hours T T

**Comment by nrikiji** [comment]
Can you tell me the version of cordova, cordova-ios, ionic because I want to try it?

**Comment by nrikiji** [comment]
I would also like to know the xcode version.

**Comment by cakeboxsolutions** [comment]
This is from ionic info  
@ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1) 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : ios 4.5.5
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node  : v10.16.3
    npm   : 6.9.0 
    OS    : macOS
    Xcode : Xcode 10.3 Build version 10G8

**Comment by cakeboxsolutions** [comment]
I use Swift 4 also.

**Comment by nrikiji** [comment]
Is carthage installed?
If you don't try, I want you to try ```ionic cordova prepare ios```

**Comment by nrikiji** [comment]
<img width="679" alt="スクリーンショット 2019-09-04 1 58 25" src="https://user-images.githubusercontent.com/4780752/64193347-8a87bf80-ceb7-11e9-83b1-b2f705e4250e.png">

Captured things should have been added to ```Linked Framework and libray```.
My Build is Success.

**Comment by nrikiji** [comment]
If this succeeds, my procedure may be incomplete ...

**Comment by cakeboxsolutions** [comment]
> Is carthage installed?
> If you don't try, I want you to try `ionic cordova prepare ios`

Very thank for this comment  before I have carthage version 3.2.0
And i try to upgrade carthage to version 3.3.0 it's work !!!
Very Sorry for mission this Requirement
https://github.com/nrikiji/cordova-plugin-carthage-support
https://github.com/akofman/cordova-plugin-add-swift-support
Carthage(>= 0.3.3)

Oh my god!

Thank for save me to night.

**Comment by nrikiji** [comment]
Oh...sorry

Is ```ionic cordova prepare ios``` not a mandatory command? 
It seems better to ```update carthage```  at the time of ```plugin add``` and ```platform add```...

I would like to confirm and correct.

**Comment by cakeboxsolutions** [comment]
> Oh...sorry
> 
> Is `ionic cordova prepare ios` not a mandatory command?
> It seems better to `carthage update` at the time of `plugin add` and `platform add`...
> 
> I would like to confirm and correct.

brew update && brew upgrade carthage
 ionic cordova platform remove ios
 ionic cordova platform add ios

**Comment by nrikiji** [comment]
fix
https://github.com/nrikiji/cordova-plugin-carthage-support/pull/3
