### ISSUE TITLE
error Android resource linking failed

### ISSUE THREAD

**Issue by danaipatra** [nrikiji/cordova-line-login-plugin#46]
is error when i run rebuild project

Android resource linking failed
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:7: error: attribute layout_constraintEnd_toEndOf (aka com.zerite.smartfixhome:layout_constraintEnd_toEndOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:7: error: attribute layout_constraintStart_toStartOf (aka com.zerite.smartfixhome:layout_constraintStart_toStartOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:7: error: attribute layout_constraintTop_toTopOf (aka com.zerite.smartfixhome:layout_constraintTop_toTopOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:22: error: attribute layout_constraintEnd_toEndOf (aka com.zerite.smartfixhome:layout_constraintEnd_toEndOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:22: error: attribute layout_constraintStart_toStartOf (aka com.zerite.smartfixhome:layout_constraintStart_toStartOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:22: error: attribute layout_constraintTop_toBottomOf (aka com.zerite.smartfixhome:layout_constraintTop_toBottomOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:39: error: attribute layout_constraintBottom_toBottomOf (aka com.zerite.smartfixhome:layout_constraintBottom_toBottomOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:51: error: attribute layout_constraintBottom_toTopOf (aka com.zerite.smartfixhome:layout_constraintBottom_toTopOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:51: error: attribute layout_constraintTop_toBottomOf (aka com.zerite.smartfixhome:layout_constraintTop_toBottomOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:58: error: attribute layout_constraintBottom_toTopOf (aka com.zerite.smartfixhome:layout_constraintBottom_toTopOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/dialog_send_message.xml:58: error: attribute layout_constraintTop_toBottomOf (aka com.zerite.smartfixhome:layout_constraintTop_toBottomOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/layout_select_target.xml:8: error: attribute layout_constraintEnd_toEndOf (aka com.zerite.smartfixhome:layout_constraintEnd_toEndOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/layout_select_target.xml:8: error: attribute layout_constraintStart_toStartOf (aka com.zerite.smartfixhome:layout_constraintStart_toStartOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/layout_select_target.xml:8: error: attribute layout_constraintTop_toTopOf (aka com.zerite.smartfixhome:layout_constraintTop_toTopOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/layout_select_target.xml:21: error: attribute layout_constraintBottom_toBottomOf (aka com.zerite.smartfixhome:layout_constraintBottom_toBottomOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/layout_select_target.xml:21: error: attribute layout_constraintEnd_toEndOf (aka com.zerite.smartfixhome:layout_constraintEnd_toEndOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/layout_select_target.xml:21: error: attribute layout_constraintStart_toStartOf (aka com.zerite.smartfixhome:layout_constraintStart_toStartOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/layout_select_target.xml:21: error: attribute layout_constraintTop_toBottomOf (aka com.zerite.smartfixhome:layout_constraintTop_toBottomOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/layout_select_target.xml:32: error: attribute layout_constraintBottom_toBottomOf (aka com.zerite.smartfixhome:layout_constraintBottom_toBottomOf) not found.
/Users/brownie/.gradle/caches/transforms-1/files-1.1/line-sdk-5.3.1.aar/f1ce6cf883d4f5220af5a5781d728037/res/layout/layout_select_target.xml:32: error: attribute layout_constraintEnd_toEndOf (aka com.zerite.smartfixhome:layout_constraintEnd_toEndOf) not found.

**Comment by danaipatra** [comment]
change android sdk 5.3.1 to 5.0.1 can resolved for me

**Comment by nrikiji** [comment]
sorry...
new project？
tel me cordova and android studio version.

**Comment by danaipatra** [comment]
cordova@9.0.0
and
android studio version 3.5.3

**Comment by nrikiji** [comment]
sorry. There seems to be an error in my verification method ... 
I reverted it once because it didn't resolve immediately.
We apologize for the inconvenience.

**Comment by nrikiji** [comment]
https://github.com/nrikiji/cordova-line-login-plugin/commit/1b230aa015def1cfae27d937ce39aed733ffd3b2

note: fix update sdk version

**Comment by danaipatra** [comment]
Thank you very much. :D
