### ISSUE TITLE
Can't build for IOS - 'LineSDK/LineSDK.h' file not found

### ISSUE THREAD

**Issue by reekoong** [nrikiji/cordova-line-login-plugin#50]
@nrikiji 
#use Xcode 11.3
Use IONIC With Capacitor

![image](https://user-images.githubusercontent.com/12757006/72276545-bcc5dc80-3662-11ea-82e9-031bbbc90ff5.png)

**Comment by nrikiji** [comment]
https://github.com/nrikiji/cordova-line- ... login-plugin/blob/dev-capacitor/README.md# capacitor

The dev branch has been updated with the necessary modifications and instructions for its implementation.
This issue will be released soon.
This issue will be closed after release.

**Comment by nrikiji** [comment]
fixed https://github.com/nrikiji/cordova-line-login-plugin/pull/60
