### ISSUE TITLE
Android app crash for no avatar user login

### ISSUE THREAD

**Issue by SheldonYS** [nrikiji/cordova-line-login-plugin#53]
When I tested with new register user which avatar is not set, the Android app crash.
Because the `profile.getPictureUrl()` at
https://github.com/nrikiji/cordova-line-login-plugin/blob/master/src/android/LineLogin.java#L78
is null. I am wondering if you have the same situation for no avatar account.

So I suggest change this line to the following code:

```
...
if (profile.getPictureUrl() != null) {
    json.put("pictureURL", profile.getPictureUrl().toString());
}
...
```

Thanks for your consideration!

**Comment by nrikiji** [comment]
Thank you for the report. Corrected.
