### ISSUE TITLE
not working only on iOS with message description":"User cancelled or interrupted the login process."

### ISSUE THREAD

**Issue by evolverr** [nrikiji/cordova-line-login-plugin#55]
Hi,

Same configuration, Same account, I success process of line login on android device.
but failed on iOS with this message

**{"sdkErrorCode":3003,"description":"User cancelled or interrupted the login process.","code":-2}**

When click LINE login button on my app, switch LINE app and every login process is ok. 
and then, switch again my app and I received this message.

please help me

**Comment by nrikiji** [comment]
thanks.
I've seen that error before too.

First of all, could you please review the settings of LineDeveloper?

Next, I'd like to ask you to check out [this issue](https://github.com/nrikiji/cordova-line-login-plugin/issues/1) and try it out.

**Comment by evolverr** [comment]
Thank you for your reply
But, I can't still complete Line login on ios

All my setting is correct iOS bundle ID, iOS universal link on Line developer.

This is my setting with example
iOS bundle ID : com.xxx.xxx
iOS universal link : https://xxx.xxx.xxx/line-auth/

and I uploaded [apple-app-site-association] file on my server.
"applinks": {
    "apps": [],
    "details": [
      {
        "appID": "TEAM_ID_APPLE.xxx.xxx.xxx",
        "paths": [ "/line-auth/*", "*" ]
      }
    ]
  }

**Comment by evolverr** [comment]
After success login on Line app, I set log on `line_application_options()` in AppDelegate+LineLogin.m,
This is logo.
 
`line3rdp.com.XXX.XXX://authorize/?code=.........&state=.........`

after then log

`{"sdkErrorCode":3003,"code":-2,"description":"User cancelled or interrupted the login process."}`

**Comment by nrikiji** [comment]
Are you using a lot of other plugins in conjunction with the ones you are trying?
If so, would you be willing to try it out on an empty project first?

**Comment by yutamatsumura** [comment]
I am also getting the same error.
When I upgraded Xcode, the plugin stopped working, and the plugin version was updated to the latest version.
I get this error when I try to login and return to the app at the end of the process.

**Comment by nrikiji** [comment]
sorry. It was a bug caused by the ios sdk update. I have verified that the login fails with sdk version 5.5.2 or later, so I'm going to take a quick look at 5.1. I fixed it with 5.5.1. I will fix it for 5.5.2 and later versions.

https://github.com/nrikiji/cordova-line-login-plugin/pull/56

**Comment by CacaoRick** [comment]
Hi, I have same error on iOS.

My universal links is work fine, after user auth in Line app, my app open again, but xcode logs show error:
{"description":"User cancelled or interrupted the login process.","sdkErrorCode":3003,"code":-2}

versions:
"@ionic-native/line-login": "^5.27.0"
"cordova-line-login-plugin": "^1.2.10"

**Comment by nrikiji** [comment]
This plugin does not support universal links, please try unsetting the "iOS universal link" setting in LINE Developers.
We would like to discuss whether or not universal link support is necessary.

**Comment by CacaoRick** [comment]
I think this problem is not relative to universal link.
If I don't set iOS universal link in LINE Developers, after auth in Line app, Line still ask me open my App.
After my App open, `LineLogin.login()` throw this error and not resolve login result.
{"sdkErrorCode":3003,"code":-2,"description":"User cancelled or interrupted the login process."}

**Comment by nrikiji** [comment]
> dev/ios-sdk-5.3.1
I'm sorry, but I'd like you to reinstall the plugin for this branch and try it out.

I think I can probably get there with it.
```
$ ionic cordova plugin rm cordova-line-login-plugin
$ ionic cordova plugin add https://github.com/nrikiji/cordova-line-login-plugin#dev/ios-sdk-5.3.1
```

**Comment by CacaoRick** [comment]
Thank you for your help.

I'm using Capacitor so I reinstall like this:
```
yarn remove cordova-line-login-plugin
yarn add https://github.com/nrikiji/cordova-line-login-plugin#dev/ios-sdk-5.3.1
npx cap sync
```
But still have same error.

**Comment by nrikiji** [comment]
Thanks for the answer.

https://github.com/nrikiji/cordova-line-login-plugin#use-in-capacitors
Can you confirm that you have fixed the AppDelegate correctly?

**Comment by CacaoRick** [comment]
Sorry i didn't notice that doc for capacitor.
After add AppDelegate fix, now login is work.
Thanks for help again.

**Comment by nrikiji** [comment]
ok thanks.
