### ISSUE TITLE
Capacitorのインストール情報

### ISSUE THREAD

**Issue by mesqueeb** [nrikiji/cordova-line-login-plugin#58]
いつもお世話になります！
Capacitorでアプリ開発をしています。（ただし、ionicではなく、Quasarというフレームワーク）

ionicと関係ないCapacitorだけのインストールと使い方のガイドの協力をお願いできますでしょうか。

ありがとうございます。

**Comment by nrikiji** [comment]
https://github.com/nrikiji/cordova-line-login-plugin/blob/dev-capacitor/README.md#capacitor

devブランチですが、こちらのブランチに必要な修正と導入手順を追記しました。
近日中にリリース予定です。
このissueはリリース後クローズとさせていただきます。

**Comment by nrikiji** [comment]
fixed https://github.com/nrikiji/cordova-line-login-plugin/pull/60
