### ISSUE TITLE
ionic capacitorでiOSビルドを行うと「'LineSDK/LineSDK.h' file not found」のエラーが出る

### ISSUE THREAD

**Issue by s-kato-nixe** [nrikiji/cordova-line-login-plugin#59]
LineSDKはCarthageで導入し、Run Scriptの追加なども行いました。
Xcode上でビルドを行うとLineSDK-Bridging-Header.hで「'LineSDK/LineSDK.h' file not found」のエラーが表示されビルドできません。

こちら解決策をご教授いただけないでしょうか。よろしくお願いします。

![スクリーンショット 2020-07-16 10 15 14](https://user-images.githubusercontent.com/57609061/87615353-82daad80-c74d-11ea-88bb-07167dded3d7.png)

**Comment by nrikiji** [comment]
https://github.com/nrikiji/cordova-line-login-plugin/blob/dev-capacitor/README.md#capacitor

devブランチですが、こちらのブランチに必要な修正と導入手順を追記しました。
近日中にリリース予定です。
このissueはリリース後クローズとさせていただきます。

**Comment by nrikiji** [comment]
fixed https://github.com/nrikiji/cordova-line-login-plugin/pull/60
