### ISSUE TITLE
AccessTokenなどの取得

### ISSUE THREAD

**Issue by kazyumaru** [nrikiji/cordova-line-login-plugin#6]
プラグインの作成と公開、心より感謝しております。
表題についてなのですが
Profileではなく、アクセストークンや
電子メールアドレスを取得し、ionic appへ値を渡したいのですが
swiftとjavaの両ファイルを読み比べていたものの
詰まってしまいました。
手がかりになるようなことをご教授いただければ幸いです。

**Comment by nrikiji** [comment]
EmailについてはLINEのドキュメントを見る限り取得できないようです。

https://developers.line.me/ja/docs/ios-sdk/managing-access-tokens/
https://developers.line.me/ja/docs/android-sdk/managing-access-tokens/
アクセストークンについてはこちらの実装が必要になります。現時点のバージョンでは対応できていないので対応しようと思います。

**Comment by nrikiji** [comment]
アクセストークン関連の処理を追加したのでクローズとさせていただきます
