### ISSUE TITLE
How can I define a "lineLogin" variable?

### ISSUE THREAD

**Issue by hsj112211** [nrikiji/cordova-line-login-plugin#69]
Hi
I use your plugin
I am testing the implementation of line login in the react source, the webview of my cordova mobile app.
But I'm not sure how to define the name lineLogin Can you help me?

- here is yore usage
![git](https://user-images.githubusercontent.com/42530484/124084208-b6f7cd00-da89-11eb-9e0c-19c0a73ce01d.PNG)

- here is my study project
- 
![local](https://user-images.githubusercontent.com/42530484/124084284-c8d97000-da89-11eb-8a17-7dd2e7a35969.PNG)
![local2](https://user-images.githubusercontent.com/42530484/124084286-ca0a9d00-da89-11eb-98b9-ad9442e1f4fa.PNG)

**Comment by nrikiji** [comment]
Do you want to solve it here?
https://github.com/nrikiji/cordova-line-login-plugin/issues/34

**Comment by hsj112211** [comment]
Thank you it has been resolved.
