### ISSUE TITLE
How to call LoginManager.setup in IOS

### ISSUE THREAD

**Issue by whitersun** [nrikiji/cordova-line-login-plugin#71]
Hello, I have using LineSDK to set up my social line login, that was success login and logout working good in android. But unfortunately, something is wrong with IOS, I don't get does it bug or not. 

Once Logout by *.logout() of line plugin, the system response to me the message "Fatal error:  [LineSDK] use AccessTokenStore before setup. Please call `LoginManager.setup` before you do any other thing in LineSDK".

When I using ios to log in is still ok, success login. But I got the above error when I take logout.

Please help!

I am using:
Ionic:

   Ionic CLI       : 6.17.1 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.7.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.2.2
   @capacitor/core    : 3.2.0
   @capacitor/ios     : 3.2.1

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.17.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.14
   OS     : Windows 10

**Comment by nrikiji** [comment]
Thank you for contacting us.
I'm sorry, I've been away from cordova and ionic development for a while. capacitor can make ios apps work on windows os?

**Comment by whitersun** [comment]
My apologize for a long time does not reply your message. I was got huge busy from last year, so I wasn't your message come in.
Actually, My laptop is windows version not Mac, So I just able test on my phone. But the problem I faced for now is after login redirect to app. I didn't get any information, but the android I have got all information, iOS I didn't saw any message.

**Comment by nrikiji** [comment]
Thank you for your answer. However, it seems to be difficult to solve the problem without tracing it on mac pc. May I close this issue?

**Comment by whitersun** [comment]
Sure, Thank you to take a busy time to answer mine question. Thanks alot
