### ISSUE TITLE
トークンの有効期限

### ISSUE THREAD

**Issue by kazyumaru** [nrikiji/cordova-line-login-plugin#8]
先日はありがとうございました。

アクセストークン取得時に
トークンの有効期限が一緒に取得できると
AWSのcognitoを経由してOpen ID connectができることがわかりました。
お忙しいところ恐縮ではありますが
トークンの有効期限の取得ができると大変助かります。

何卒よろしくお願いいたします。

**Comment by nrikiji** [comment]
getAccessTokenの戻り値にexpireTImeを追加しました。
必要であれば別途メソッドの追加も検討します。
